<Project Sdk="Microsoft.NET.Sdk">
  <Choose>
    <When Condition="'$(Configuration)' == 'ReleaseWindows' OR '$(Configuration)' == 'DebugWindows'">
      <PropertyGroup>
        <TargetFrameworks>net10.0-windows</TargetFrameworks>
        <DefineConstants>$(DefineConstants);WPF</DefineConstants>
        <Title>GameshowPro mDNS wrapper - Windows version</Title>
        <UseWpf>true</UseWpf>
        <UseWindowsForms>true</UseWindowsForms>
        <PackageId>GameshowPro.Mdns.Windows</PackageId>
      </PropertyGroup>
      <ItemGroup>
        <PackageReference Include="GameshowPro.Common.Windows" Version="1.3.7" />
      </ItemGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <Title>GameshowPro mDNS wrapper - Cross platform version</Title>
        <PackageId>GameshowPro.Mdns</PackageId>
      </PropertyGroup>
      <ItemGroup>
        <None Include="**\*.xaml" />
        <Compile Remove="**\*.xaml.cs" />
      </ItemGroup>
      <ItemGroup>
        <PackageReference Include="GameshowPro.Common" Version="1.3.7" />
      </ItemGroup>
    </Otherwise>
  </Choose>
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Hamish Barjonas</Authors>
    <Product>GameshowPro mDNS wrapper</Product>
    <Description>A wrapper around a lower level mDNS implemenation to allow easy and consistent implementation within GameShowPro applications.</Description>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <Copyright>Barjonas LLC 2026</Copyright>
    <PackageTags>multicast mdns dns zeroconf</PackageTags>
    <IncludeSymbols>True</IncludeSymbols>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <Configurations>Debug;Release;ReleaseWindows;DebugWindows</Configurations>
    <OutputPath>bin\$(Configuration)</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>
	<ItemGroup>
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.10.91">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Makaretu.Dns.Multicast.Gsp" Version="1.0.6" />
	</ItemGroup>
</Project>
