global using System.Collections.Concurrent;
global using System.Collections.Immutable;
global using System.Collections.Frozen;
global using System.Diagnostics;
global using System.Net;
global using System.Diagnostics.CodeAnalysis;
global using Microsoft.Extensions.Logging;
global using Makaretu.Dns;
global using GameshowPro.Common.Model;
global using GameshowPro.Common;
global using static GameshowPro.Mdns.Constants;
